services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: my-python-app:latest
    volumes:
      - .:/app
    command: ["python", "multi_account_with_env.py"]
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
