services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aqw-bot:latest
    volumes:
      - .:/app
    command: ["python", "main-web.py"]
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
